[package]
name = "agentplane-cli"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "agentplane"
path = "src/main.rs"

[dependencies]
agent-core.workspace = true
agentplane-client.workspace = true
agentplane-core.workspace = true
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
