{{- if and .Values.fleetConfiguration.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agentdesktop-controller.serviceAccountName" . }}
  labels:
    {{- include "agentdesktop-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if and .Values.fleetConfiguration.enabled .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "agentdesktop-controller.fullname" . }}-fleet-configuration
  labels:
    {{- include "agentdesktop-controller.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames:
  - {{ include "agentdesktop-controller.fleetConfigurationName" . }}
  verbs: ["get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "agentdesktop-controller.fullname" . }}-fleet-configuration
  labels:
    {{- include "agentdesktop-controller.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "agentdesktop-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "agentdesktop-controller.fullname" . }}-fleet-configuration
{{- end }}