apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentdesktop-controller.fullname" . }}
  labels:
    {{- include "agentdesktop-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "agentdesktop-controller.selectorLabels" . | nindent 4 }}
  ports:
  - name: fleet
    port: {{ .Values.service.port }}
    targetPort: fleet
    protocol: TCP

