# yaml-language-server: $schema=../../schema/daemon-config.json
llmGateway:
  url: http://127.0.0.1:4001
  authentication:
    type: oidc
    issuer: http://127.0.0.1:5557/dex
    clientId: agentdesktop-local
    scopes: [openid, email, offline_access]
    allowInsecure: true

programs:
  claudeCode:
    useLlmGateway: true
    companyAnnouncements: ["Using the local Agentgateway through Agentdesktop"]
#    Claude desktop cannot run with --user. Uncomment to enable
  claudeDesktop:
    useLlmGateway: true
